project:
  type: website
  output-dir: docs

website:
  title: "CoreyGW.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
        text: Projects
      - href: Links.qmd
        text: Links

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



